### ISSUE TITLE
Cannot use wg interface for outgoing udp connection

### ISSUE THREAD

**Issue by droscy** [droscy/esphome#1]
See comments:
- https://github.com/esphome/feature-requests/issues/1444#issuecomment-1557961980
- https://github.com/esphome/feature-requests/issues/1444#issuecomment-1565228349

@snechiporenko I've opened this issue to track your issue and to have dedicated discussion.

**Comment by droscy** [comment]
@snechiporenko will it work if you set netmask to `0.0.0.0`?

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/droscy/esphome
      ref: wireguard/main
    components:
      - wireguard

wireguard:
  address: 172.27.66.4
  netmask: 0.0.0.0
  [...]
```

**Comment by snechiporenko** [comment]
Hello. Yes! Now it work.

```
[D][main:102]: Received 512 bytes
[D][binary_sensor:036]: 'button': Sending state OFF
[D][voice_assistant:113]: Signaling stop...
[D][voice_assistant:137]: Speech recognised as: "Test."
[D][wireguard:057]: WireGuard remote peer is online (latest handshake 2023-05-28 18:12:00 EEST)
[D][voice_assistant:152]: Response: "I'm sorry, I'm not sure what you're protesting about. Can you please provide more context or information so I can better understand your concerns?"
[D][voice_assistant:167]: Response URL: "http://192.168.31.111:8123/api/tts_proxy/001d97e429c2797d8e106d17e07a66f395edda05_ru-ru_068aae5954_cloud.mp3"
[D][voice_assistant:172]: Assist Pipeline ended
```
Can you explain why it happened?

I still want to test [Speaker](https://esphome.io/components/speaker/index.html) and [Media Player](https://esphome.io/components/media_player/index.html) integrations, but I don't have the technical ability to do so yet.

Thank you very much for the useful component. I'm waiting for it to become standard.

**Comment by droscy** [comment]
Probably it is the same issue of #2 and actually I don't know if it is really an issue. It could be a wrong initialization of the network interface or it could be the intended behaviour of lwip stack. I wiil investigate further.

However what is happening is that netmask is directly linked to routing table so if you set

```yaml
wireguard:
  address: 172.27.66.4
  netmask: 255.255.255.255  # default if omitted
  peer_allowed_ips: [0.0.0.0/0]  # default if omitted
```

wireguard will accept any packet BUT the system will use wireguard interface for outging packets only for 172.27.66.4/32, only that single host!

If your Home Assistant's wireguard IP is `172.30.32.1` and esp device has `172.27.66.4` you should set at least

```yaml
wireguard:
  address: 172.27.66.4
  netmask: 255.0.0.0  # the equivalent of /8
  peer_allowed_ips:
    - 172.27.66.0/24  # or what your netmask is
    - 172.30.32.0/24  # or what your netmask is
```

or, of course, `0.0.0.0` for netmask removing `peer_allowed_ips`.

**Comment by droscy** [comment]
@snechiporenko could you confirm that the following is working either?

```yaml
wireguard:
  address: 172.27.66.4
  netmask: 255.0.0.0  # the equivalent of /8
  peer_allowed_ips:
    - 172.27.66.0/24  # or what your netmask is
    - 172.30.32.0/24  # or what your netmask is
```

So we can consider this issue resolved.
