### ISSUE TITLE
Wireguard refresh on local network connection loss

### ISSUE THREAD

**Issue by droscy** [droscy/esphome#11]
See the following comments https://github.com/esphome/feature-requests/issues/1444#issuecomment-1606072316 and https://github.com/esphome/feature-requests/issues/1444#issuecomment-1608898283

Testing a way to hook local network connection loss.

**Comment by droscy** [comment]
@snechiporenko could you test branch `fix/wg/wifi_disconnect` while disabling (or loosing) wifi connection? Thanks

```
external_components:
  - source:
      type: git
      url: https://github.com/droscy/esphome
      ref: fix/wg/wifi_disconnect
    components: [wireguard]

wireguard:
  # configure as usual
```
