### ISSUE TITLE
Integrate sensors inside wireguard component itself

### ISSUE THREAD

**Issue by droscy** [droscy/esphome#8]
As per comment here https://github.com/esphome/esphome/pull/4256#pullrequestreview-1474047873 the two sensors must be integrated in wireguard component itself.

This should be the config

```yaml

wireguard:
  ...
  
sensor:
  - platform: wireguard
    latest_handshake: 
      name: WireGuard Latest Handshake
    <future sensors exposed>

binary_sensor:
  - platform: wireguard
    status:
      name: WireGuard Status
    <future binary sensors exposed>
```
